# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PostHiveCompanion' do
  config = use_native_modules!
  use_expo_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix build settings for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        
        # Disable code signing for static libraries (they don't need it)
        build_config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        build_config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        build_config.build_settings['CODE_SIGN_IDENTITY'] = ''
        
        # Fix react-native-document-picker: add ReactCodegen header path for rndocumentpicker.h (New Architecture)
        if target.name == 'react-native-document-picker'
          codegen_path = File.join(Pod::Config.instance.installation_root, 'build/generated/ios/ReactCodegen')
          build_config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited)'
          build_config.build_settings['HEADER_SEARCH_PATHS'] << " \"#{codegen_path}\""
        end
      end
    end
  end
end
